/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ReflexAfterSwapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getConfigId"
      | "getRouter"
      | "setReflexConfigId"
      | "setReflexRouter"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ReflexConfigIdUpdated" | "ReflexRouterUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getConfigId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getRouter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setReflexConfigId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReflexRouter",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getConfigId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReflexConfigId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReflexRouter",
    data: BytesLike
  ): Result;
}

export namespace ReflexConfigIdUpdatedEvent {
  export type InputTuple = [oldConfigId: BytesLike, newConfigId: BytesLike];
  export type OutputTuple = [oldConfigId: string, newConfigId: string];
  export interface OutputObject {
    oldConfigId: string;
    newConfigId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReflexRouterUpdatedEvent {
  export type InputTuple = [oldRouter: AddressLike, newRouter: AddressLike];
  export type OutputTuple = [oldRouter: string, newRouter: string];
  export interface OutputObject {
    oldRouter: string;
    newRouter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReflexAfterSwap extends BaseContract {
  connect(runner?: ContractRunner | null): ReflexAfterSwap;
  waitForDeployment(): Promise<this>;

  interface: ReflexAfterSwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getConfigId: TypedContractMethod<[], [string], "view">;

  getRouter: TypedContractMethod<[], [string], "view">;

  setReflexConfigId: TypedContractMethod<
    [_configId: BytesLike],
    [void],
    "nonpayable"
  >;

  setReflexRouter: TypedContractMethod<
    [_router: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getConfigId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setReflexConfigId"
  ): TypedContractMethod<[_configId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReflexRouter"
  ): TypedContractMethod<[_router: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ReflexConfigIdUpdated"
  ): TypedContractEvent<
    ReflexConfigIdUpdatedEvent.InputTuple,
    ReflexConfigIdUpdatedEvent.OutputTuple,
    ReflexConfigIdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReflexRouterUpdated"
  ): TypedContractEvent<
    ReflexRouterUpdatedEvent.InputTuple,
    ReflexRouterUpdatedEvent.OutputTuple,
    ReflexRouterUpdatedEvent.OutputObject
  >;

  filters: {
    "ReflexConfigIdUpdated(bytes32,bytes32)": TypedContractEvent<
      ReflexConfigIdUpdatedEvent.InputTuple,
      ReflexConfigIdUpdatedEvent.OutputTuple,
      ReflexConfigIdUpdatedEvent.OutputObject
    >;
    ReflexConfigIdUpdated: TypedContractEvent<
      ReflexConfigIdUpdatedEvent.InputTuple,
      ReflexConfigIdUpdatedEvent.OutputTuple,
      ReflexConfigIdUpdatedEvent.OutputObject
    >;

    "ReflexRouterUpdated(address,address)": TypedContractEvent<
      ReflexRouterUpdatedEvent.InputTuple,
      ReflexRouterUpdatedEvent.OutputTuple,
      ReflexRouterUpdatedEvent.OutputObject
    >;
    ReflexRouterUpdated: TypedContractEvent<
      ReflexRouterUpdatedEvent.InputTuple,
      ReflexRouterUpdatedEvent.OutputTuple,
      ReflexRouterUpdatedEvent.OutputObject
    >;
  };
}
