/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ReflexAfterSwap,
  ReflexAfterSwapInterface,
} from "../../../../contracts/plugins/reflex-mev/ReflexAfterSwap";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "oldConfigId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "newConfigId",
        type: "bytes32",
      },
    ],
    name: "ReflexConfigIdUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldRouter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newRouter",
        type: "address",
      },
    ],
    name: "ReflexRouterUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "getConfigId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRouter",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_configId",
        type: "bytes32",
      },
    ],
    name: "setReflexConfigId",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_router",
        type: "address",
      },
    ],
    name: "setReflexRouter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ReflexAfterSwap__factory {
  static readonly abi = _abi;
  static createInterface(): ReflexAfterSwapInterface {
    return new Interface(_abi) as ReflexAfterSwapInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReflexAfterSwap {
    return new Contract(address, _abi, runner) as unknown as ReflexAfterSwap;
  }
}
