name: Checks

on:
  push:
    branches:
      - integral-v1.2.1
  pull_request:
    branches:
      - integral-v1.2.1

jobs:
  Codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@v2.0
        with:
          check_hidden: true
          check_filenames: true
          skip: package-lock.json,node_modules,Base64.spec.ts.snap
          only_warn: 1
