name: Autotests Farmings

on:
  push:
    branches:
      - integral-v1.2.1
  pull_request:
    branches:
      - integral-v1.2.1

jobs:
  Autotests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/farming

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm run bootstrap
        working-directory: ./
      - run: npm run compile
      - run: npm run test
